### ISSUE TITLE
Add a CONTRIBUTING book to replace the scattered resources about how to contribute

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy-website#1146]
## Motivation

The existing https://github.com/bevyengine/bevy/blob/main/CONTRIBUTING.md is generally far too long for a single page, and painful to read as a long block of markdown.

We also have scattered information throughout the project about how things are run:

- [The Bevy Organization](https://github.com/bevyengine/bevy/blob/main/docs/the_bevy_organization.md)
- [Release Checklist](https://github.com/bevyengine/bevy/blob/main/docs/release_checklist.md)
- [Linters](https://github.com/bevyengine/bevy/blob/main/docs/linters.md)
- [Engine Style Guide](https://github.com/bevyengine/bevy/blob/main/.github/contributing/engine_style_guide.md)
- [Example Style Guide](https://github.com/bevyengine/bevy/blob/main/.github/contributing/example_style_guide.md)
- [bevy_website CONTRIBUTING](https://github.com/bevyengine/bevy-website/blob/main/CONTRIBUTING.md)

That are somehow even less discoverable. Most of these were deemed too irrelevant and distracting to put into the main CONTRIBUTING.md (valid!), but that means they serve no practical purpose to 99% of contributors who have no idea that they exist.

We have a solution for "structured, long-form content with multiple pages that we want high visibility for": books hosted on the bevyengine.org domain.

## Solution

- [ ] Create a new book (using all of the existing styling and tooling of the existing quick start guide and in-depth book) in this repo. Make it hidden for now.
- [ ] Copy all of the existing content into that book.
- [ ] Do a brief cleanup pass.
- [ ] Make it visible under a new top-level `Contribute` header beside "Foundation".
- [ ] Replace the main CONTRIBUTING.md in each repo with a link to the appropriate section of the book.

**Comment by cart** [comment]
I'm on board for this! Only first-impression note is that we might want to avoid use of the word "Book" in the final published result, just to avoid confusion/overlap with "The Bevy Book".

**Comment by TrialDragon** [comment]
Regarding `The Bevy Organization` document, it'd probably work best as having it's info moved to the community people page of the site; already has same basic information, just needs to be expanded upon with details. If so, then that can probably be spun out into it's own issue separate of the Contributor's Guide (name that seems to have picked up traction in Discord so far).

**Comment by BD103** [comment]
For future reference, this is being worked on by the Contributor's Guide working group [on Discord](https://discord.com/channels/691052431525675048/1236112637662724127) with an in-progress design doc on [hackmd.io](https://hackmd.io/@nth/contributors_guide).
