### ISSUE TITLE
tracking issue: migration to Bevy Assets

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy-website#159]
# Bevy Website repo

- [x] Generate Zola pages from Bevy Assets repo
  - [x] First pass with minimal fields - https://github.com/bevyengine/bevy-website/pull/156
  - [x] Crate can generate the website - https://github.com/bevyengine/bevy-website/pull/156
  - [x] Setup CI - https://github.com/bevyengine/bevy-website/pull/156
  - [x] Crate can validate the input - #163 
- [x] Remove other references to Awesome Bevy - #165
- [ ] Metadata of assets
  - [x] Image support - #163
  - [ ] Agree on complete format and additional fields we want
  - [x] Enrich with crates.io data (license, Bevy version, ...) - https://github.com/alyti/populate-crate-metadata
  - [ ] Enrich with github data (stars? not sure it's possible without hitting GitHub api limits)
  - [ ] Enrich with other potential sources (gitlab? our own database for ❤️?)
- [ ] Website views
  - [x] Basic list view - https://github.com/bevyengine/bevy-website/pull/156
  - [ ] Add a text explanation on what it is and how to add your own stuff, and link to Bevy Assets repo
  - [ ] Add a page view per asset - [Figma design ideas](https://www.figma.com/proto/BAWOVsxMB8JrQnfpGaIAIW/Bevy-Store?node-id=2%3A1&scaling=min-zoom&page-id=0%3A1)
  - [x] Asset search
  - [x] Prettier small cards in list view
  - [ ] Assets can have one primary tag and several secondary tags, can filter on tag

# Bevy Assets repo

- [x] Updated the readme to help with automatic migration:
  - [x] Changed headers - https://github.com/bevyengine/awesome-bevy/pull/102
  - [x] Remove markdown links - https://github.com/bevyengine/awesome-bevy/pull/102
  - [x] Script for automatic migration - https://github.com/bevyengine/bevy-website/pull/156
  - [x] Automatic migration - https://github.com/bevyengine/awesome-bevy/pull/102
- [x] Repo setup for new Bevy Assets:
  - [x] Setup order for some items - https://github.com/bevyengine/awesome-bevy/pull/102
  - [x] Setup CI to validate new files added in a PR - https://github.com/bevyengine/awesome-bevy/pull/105
  - [x] Setup CI to trigger bevy-website publish - https://github.com/bevyengine/awesome-bevy/pull/105
  - [x] Update the readme (specify new way, describe format, link to Bevy Assets) - https://github.com/bevyengine/awesome-bevy/pull/105
  - [x] Update migrations with Assets added since branch creation - https://github.com/bevyengine/awesome-bevy/pull/108
  - [x] Switch branch
  - [x] Rename the repo - https://github.com/bevyengine/bevy-website/pull/165
- [ ] Enrich initial repo
  - [x] Fix assets for new constraints (description without markdown and 100 chars limit) - https://github.com/bevyengine/awesome-bevy/pull/105
  - [ ] Ask for contributors to add pictures, new metadata, ...

**Comment by mockersf** [comment]
close enough to be done for that step - I will try to open a new tracking issue soon for the next step
