### ISSUE TITLE
tracking issue: examples

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy-website#299]
https://github.com/bevyengine/bevy-website/pull/225 introduced a new page for wasm examples at https://bevyengine.org/examples/

This page is currently lacking in style and not linked from the website. I think it should be the main page for example discovery instead of the git repo:
* it is easier to ensure that the examples are at the latest tag instead of main as the website is only about latest
* it is easier to evolve organisation with tags and categories instead of just a list of folders
* it is easier to control presentation as GitHub will always show files first, then the optional readme.md
* it is easier to have a nice presentation instead of just one large and basic readme.md

So... in case it's not clear, I think it would be easier.

What would be needed to get it in top shape:

- [ ] add a metadata file / header for each example describing what it does, if it should be built for wasm
  - title
  - description
- [ ] update the website to display all examples with their metadata, but only build wasm version for the one where it is enabled
- [ ] link more prominently to the website for examples
- [ ] (optional) add screenshot of the examples as part of the metadata
- [ ] (optional) remove/simplify the readme.md in bevy repo example folder. This file can't scale
- [ ] (optional) add tags to the metadata to help with discovery

This should be tied with https://github.com/bevyengine/bevy-website/issues/159 (bevy assets page) to evolve a consistent style.

**Comment by cart** [comment]
I love these ideas. Is there a good way to specify custom per-example metadata in Cargo.toml? I think id prefer that if its possible. If not, a single centralized file for this config has my preference. I dont want to throw a bunch of metadata in custom per file header format, or have a bunch of per-example config files. That could be weird/confusing for users.

**Comment by mockersf** [comment]
> Is there a good way to specify custom per-example metadata in Cargo.toml?

It's possible to add any field we want in the `Cargo.toml` file:

```toml
[[example]]
name = "3d_scene"
path = "examples/3d/3d_scene.rs"
display_name = "3D Scene"
description = "Simple 3D scene with basic shapes and lighting"
```

but this issues warnings:

```
warning: /bevy/Cargo.toml: unused manifest key: example.13.description
warning: /bevy/Cargo.toml: unused manifest key: example.13.display_name
```

**Comment by cart** [comment]
Maybe we could use this: https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table?

```rust
[[example]]
name = "3d_scene"
path = "examples/3d/3d_scene.rs"

[package.metadata.example.3d_scene]
display_name = "3D Scene"
description = "Simple 3D scene with basic shapes and lighting"
```

**Comment by cart** [comment]
Sadly a bit verbose + redundant (`example.3d_scene` would need to match `name = "3d_scene"`), but it might work :)

**Comment by mockersf** [comment]
I would love for this to work:

```toml
[[example]]
name = "3d_scene"
path = "examples/3d/3d_scene.rs"

[example.metadata]
display_name = "3D Scene"
description = "Simple 3D scene with basic shapes and lighting"
```
[Array of Tables](https://toml.io/en/v1.0.0#array-of-tables): Any reference to an array of tables points to the most recently defined table element of the array. This allows you to define sub-tables, and even sub-arrays of tables, inside the most recent table. That means the metadata field would refer to the example defined just above

I looked a little into cargo code, it wouldn't be hard to ask, I'll check if they would accept a PR for that

**Comment by BD103** [comment]
Here is an updated checklist:

- [x] add metadata to Cargo.toml about each example https://github.com/bevyengine/bevy/pull/4741
- [ ] ~~add an example page built with the dev docs~~
  - Given how building all of the WASM examples takes roughly [2.5 hours](https://github.com/bevyengine/bevy-website/actions/workflows/build-wasm-examples.yml), I don't think this is viable
- [ ] update the website to display all examples with their metadata, but only build wasm version for the one where it is enabled
  - Related: #1024
- [ ] remove/simplify the readme.md in bevy repo example folder. This file can't scale
  - Perhaps an individual `README.md` can be created per subdirectory: one for `2d`, one for `ecs`, etc.
- [x] link more prominently to the website for examples https://github.com/bevyengine/bevy-website/pull/335
- [x] (optional) add screenshot of the examples as part of the metadata
- [x] (optional) add tags to the metadata to help with discovery
